# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json


###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 389eddc575d6e445b7d620ff6bb1502f7cf56da2

{
  "title": "7",
  "description": "7",
  "status": "OPEN"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/8/
Content-Type: application/json
Authorization: Token 389eddc575d6e445b7d620ff6bb1502f7cf56da2

{
  "status": "CLOSED",
  "description":"Новое"
}


###

# попытка удалить объявление
DELETE  {{baseUrl}}/advertisements/10/
Content-Type: application/json
Authorization: Token fc00afba9fa57a400900419b444647f4b78843b9

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3&status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json


###

# посмотреть объявление в избранном
GET {{baseUrl}}/advertisements/favorite_list/
Content-Type: application/json
Authorization: Token fc00afba9fa57a400900419b444647f4b78843b9

###

# удалить объявление из избранного
DELETE {{baseUrl}}/advertisements/1/favorite_delete/
Content-Type: application/json
Authorization: Token fc00afba9fa57a400900419b444647f4b78843b9

###

# добавление объявления в избранное
POST {{baseUrl}}/advertisements/11/favorite_add/
Content-Type: application/json
Authorization: Token bfb7ccf1c427631568ae345d51ec45314aad1851

