# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2fed88c08d5097b1521fcd8c257113a3d83eb4ec

{
  "title": "Кровать МирСтулМорсуы",
  "description": "цуацуа",
  "status": "CLOSED"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/53/
Content-Type: application/json
Authorization: Token 2fed88c08d5097b1521fcd8c257113a3d83eb4ec

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
